# @package _global_

model:
  name: BERT
  _meta_data: ${_llm_md_lookup.${.base_model}}
  local_dir: ${env.path.hf_local}${.base_model}/
  base_model: deberta-large
  hf_name: ${._meta_data.hf_name}
# Model parameters
bert_emb_file: emb/${alias}_emb.memmap
inf_batch_size: ${oc.select:model._meta_data.inf_bsz,12}

emb_file: emb/data/${model.base_model}/${model.base_model}_emb.pth
cache_file_name: ${env.path.slurm_tmp_dir}data_cache/${data.name}/${data.subset_class}${data.sample_per_class}${data.process_mode}-${model.base_model}.cache
wandb_proj: MPLM-Deberta