# @package _global_

model:
  name: GraphSAGE
  init_args:
    _target_: gnn.graphsage.GraphSAGE
    n_layers: ${n_layers}
    n_hidden: ${n_hidden}
    n_classes: ${data.n_labels}
    in_feats: ${data.feat_dim}
    dropout: ${dropout}
    num_workers: 0
# Model parameters
num_workers: 0
fanout: [1, 2]
batch_size: 64
weight_decay: 5e-4
n_layers: 2
norm: BN
dropout: 0.6
epochs: 100
eval_freq: 200
n_hidden: 128
lr: 0.005

# Training settings
save_hidden: false
alias: ${data.name}/${n_layers}layer${model.name}_lr${lr}_h${n_hidden}_do${dropout}
emb_file: emb/${alias}_emb.pth
eval_metric: val_acc
wandb_proj: MPLM-GNN