# @package _global_
env:
  vars: # @ To be initialized by os.env
    wandb_proj: MPLM-Debug
logging:
  level: debug
debug: true
data:
  max_eval_samples: 50
  max_test_samples: 50
total_steps: 50
eval_freq: 20